apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
  namespace: default
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: royeb/polybot:v1.1.17
          ports:
            - containerPort: 8443
          env:
            - name: TELEGRAM_APP_URL
              value: "royeb.devops-int-college.com"
            - name: BUCKET_NAME
              value: "royeb-k8s"
            - name: SQS_URL
              value: "https://sqs.eu-north-1.amazonaws.com/352708296901/royeb-sqs"
            - name: TELEGRAM_TOKEN
              value: "8134126918:AAGahsP2LQ7T_ZNv8Zb8vLzKPVPXBJIqBl4"
            - name: POLYBOT_RESULTS_URL
              value: "8134126918:AAGahsP2LQ7T_ZNv8Zb8vLzKPVPXBJIqBl4"
