apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
  namespace: default
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: royeb/polybot:v1.1.13
          ports:
            - containerPort: 8443
          env:
            - name: TELEGRAM_APP_URL
              value: "https://0c2c-5-29-23-65.ngrok-free.app"
            - name: S3_BUCKET_NAME
              value: "royeb-k8s"
            - name: SQS_URL
              value: "https://sqs.eu-north-1.amazonaws.com/352708296901/royeb-sqs"
