apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongo-init
          image: mongo:5
          command: ["sh", "-c"]
          args:
            - |
              until mongosh --host mongodb-0.mongodb:27017 --eval "print('MongoDB is up')" >/dev/null 2>&1; do
                sleep 10
              done
              mongosh --host mongodb-0.mongodb.default.svc.cluster.local --eval '
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongodb-0.mongodb:27017", priority: 2 },
                  { _id: 1, host: "mongodb-1.mongodb:27017", priority: 1 },
                  { _id: 2, host: "mongodb-2.mongodb:27017", priority: 1 }
                ]
              })'