apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None  # Headless Service for StatefulSet
  selector:
    app: mongodb  # Select pods from the StatefulSet
  ports:
  - port: 27017    # MongoDB default port
    name: mongo
