apiVersion: v1
kind: Service
metadata:
  name: yolo5-service
  namespace: default
spec:
  selector:
    app: yolo5
  ports:
    app: yolo5
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081